### ISSUE TITLE
new version in NPM

### ISSUE THREAD

**Issue by felipesousa** [jaredly/hexo-admin#27]
I see you created a new version, `1.1.0` that support the version of x3.0.0 hexo, I wonder when will publish it in the NPM.

**Comment by DexterYan** [comment]
same question. I have face a error in current version 0.1.2. 
```
ERROR Plugin load failed: hexo-admin-plugin
ReferenceError: hexo is not defined
```
my hexo version
```
hexo: 3.1.0
os: Darwin 13.4.0 darwin x64
http_parser: 2.3
node: 0.12.7
v8: 3.28.71.19
uv: 1.6.1
zlib: 1.2.8
modules: 14
openssl: 1.0.1p
```

**Comment by jaredly** [comment]
I published 1.1.0 yesterday, and 1.1.1 today (which fixed some dependencies)

**Comment by ianpogi5** [comment]
I'm still getting 0.1.2. Am I missing something?

https://www.npmjs.com/package/hexo-admin-plugin

<img width="1171" alt="screen shot 2015-09-30 at 12 20 18 pm" src="https://cloud.githubusercontent.com/assets/1063875/10184330/c98b90a4-676d-11e5-99f5-adf19a71642b.png">

**Comment by ianpogi5** [comment]
Made a pull request #30 to fix the issue
